apiVersion: v1
items:

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: The web server's http port.
        service.alpha.openshift.io/dependencies: '[{"name":"coolstore-postgresql","namespace":"","kind":"Service"}]'
      labels:
        application: coolstore
        template: coolstore-monolith-binary-demo
      name: coolstore
    spec:
      ports:
      - port: 8080
        targetPort: 8080
      selector:
        deploymentConfig: coolstore
 
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: The database server's port.
      labels:
        application: coolstore
        template: coolstore-monolith-binary-demo
      name: coolstore-postgresql
    spec:
      ports:
      - port: 5432
        targetPort: 5432
      selector:
        deploymentConfig: coolstore-postgresql

  - apiVersion: route.openshift.io/v1
    id: coolstore-http
    kind: Route
    metadata:
      annotations:
        description: Route for application's http service.
      labels:
        application: coolstore
        template: coolstore-monolith-binary-demo
      name: www
    spec:
      to:
        name: coolstore
 
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        application: coolstore
        build: coolstore
        template: coolstore-monolith-binary-demo
      name: coolstore

kind: List
metadata: {}