apiVersion: v1
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: coolstore
        template: coolstore-monolith-binary-demo
      name: coolstore
    spec:
      replicas: 1
      selector:
        deploymentConfig: coolstore
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            application: coolstore
            deploymentConfig: coolstore
          name: coolstore
        spec:
          containers:
          - env:
            - name: DB_SERVICE_PREFIX_MAPPING
              value: coolstore-postgresql=DB
            - name: DB_JNDI
              value: java:jboss/datasources/CoolstoreDS
            - name: DB_USERNAME
              value: coolstore
            - name: DB_PASSWORD
              value: coolstore123
            - name: DB_DATABASE
              value: monolith
            - name: TX_DATABASE_PREFIX_MAPPING
              value: coolstore-postgresql=DB
            - name: OPENSHIFT_KUBE_PING_LABELS
              value: application=coolstore
            - name: OPENSHIFT_KUBE_PING_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HTTPS_KEYSTORE_DIR
              value: /etc/eap-secret-volume
            - name: HTTPS_KEYSTORE
              value: keystore.jks
            - name: HTTPS_KEYSTORE_TYPE
              value: JKS
            - name: HTTPS_NAME
              value: jboss
            - name: HTTPS_PASSWORD
              value: mykeystorepass
            - name: MQ_CLUSTER_PASSWORD
              value: coolstore123
            - name: JGROUPS_ENCRYPT_SECRET
              value: coolstore-secret
            - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
              value: /etc/jgroups-encrypt-secret-volume
            - name: JGROUPS_ENCRYPT_KEYSTORE
              value: jgroups.jceks
            - name: JGROUPS_ENCRYPT_NAME
              value: secret-key
            - name: JGROUPS_ENCRYPT_PASSWORD
              value: password
            - name: JGROUPS_CLUSTER_PASSWORD
              value: openshift123
            - name: DEFAULT_JOB_REPOSITORY
              value: coolstore-postgresql
            - name: TIMER_SERVICE_DATA_STORE
              value: coolstore-postgresql
            image: coolstore
            imagePullPolicy: Always
            lifecycle:
              preStop:
                exec:
                  command:
                  - /opt/eap/bin/jboss-cli.sh
                  - -c
                  - :shutdown(timeout=60)
            livenessProbe:
              exec:
                command:
                - /bin/bash
                - -c
                - /opt/eap/bin/livenessProbe.sh
            name: coolstore
            ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8888
              name: ping
              protocol: TCP
            readinessProbe:
              failureThreshold: 5
              httpGet:
                path: /health.jsp
                port: 8080
                scheme: HTTP
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 1
            volumeMounts:
            - mountPath: /etc/eap-secret-volume
              name: eap-keystore-volume
              readOnly: true
            - mountPath: /etc/jgroups-encrypt-secret-volume
              name: eap-jgroups-keystore-volume
              readOnly: true
          serviceAccountName: coolstore-serviceaccount
          terminationGracePeriodSeconds: 75
          volumes:
          - name: eap-keystore-volume
            secret:
              secretName: coolstore-secret
          - name: eap-jgroups-keystore-volume
            secret:
              secretName: coolstore-secret
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - coolstore
          from:
            kind: ImageStreamTag
            name: coolstore:latest
        type: ImageChange
      - type: ConfigChange
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: coolstore
        template: coolstore-monolith-binary-demo
      name: coolstore-postgresql
    spec:
      replicas: 1
      selector:
        deploymentConfig: coolstore-postgresql
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: coolstore
            deploymentConfig: coolstore-postgresql
          name: coolstore-postgresql
        spec:
          containers:
          - env:
            - name: POSTGRESQL_USER
              value: coolstore
            - name: POSTGRESQL_PASSWORD
              value: coolstore123
            - name: POSTGRESQL_DATABASE
              value: monolith
            image: postgresql
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 5432
              timeoutSeconds: 1
            name: coolstore-postgresql
            ports:
            - containerPort: 5432
              protocol: TCP
            readinessProbe:
              exec:
                command:
                - /bin/sh
                - -i
                - -c
                - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                  'SELECT 1'
              failureThreshold: 3
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
          terminationGracePeriodSeconds: 60
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - coolstore-postgresql
          from:
            kind: ImageStreamTag
            name: postgresql:latest
            namespace: openshift
        type: ImageChange
      - type: ConfigChange
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        template: coolstore-monolith-binary-demo
      name: coolstore-serviceaccount
    secrets:
    - name: coolstore-secret
  - apiVersion: authorization.openshift.io/v1
    groupNames: null
    kind: RoleBinding
    metadata:
      labels:
        template: coolstore-monolith-binary-demo
      name: coolstore-serviceaccount_view
    roleRef:
      name: view
    subjects:
    - kind: ServiceAccount
      name: coolstore-serviceaccount
  - apiVersion: authorization.openshift.io/v1
    groupNames:
    - system:serviceaccounts:ci
    kind: RoleBinding
    metadata:
      labels:
        template: coolstore-monolith-binary-demo
      name: ci_admin
    roleRef:
      name: admin
    subjects:
    - kind: SystemGroup
      name: system:serviceaccounts:ci
kind: List
metadata: {}