- name: Deploy Coolstore Stack on OCP
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Create Coolstore namespace {{ eap_ocp_namespace }}
      k8s:
        state: present
        name: "{{ eap_ocp_namespace }}"
        api_version: project.openshift.io/v1
        kind: Project
        validate_certs: no

    - name: Create Coolstore objects in {{ eap_ocp_namespace }}
      k8s:
        state: present
        namespace: "{{ eap_ocp_namespace }}"
        definition: "{{ lookup('file', 'definition.yml') }}"
        validate_certs: no

    - name: Create Coolstore secrets {{ eap_ocp_namespace }}
      k8s:
        state: present
        namespace: "{{ eap_ocp_namespace }}"
        definition: "{{ lookup('template', 'jboss_secrets.j2') }}"
        validate_certs: no

    - name: Select Artifact 
      set_fact:
        artifact: "{{ artifact_store | regex_replace('/$','') }}/{{ war_name }}-{{ version }}.war"
 
    - name: Get WAR
      get_url:
        url: "{{ artifact }}"
        dest: /tmp/ROOT.war
        force: yes
      delegate_to: localhost

    - name: Run the build
      shell:  |
        oc login --insecure --token={{ lookup('env','K8S_AUTH_API_KEY') }} --server={{ lookup('env','K8S_AUTH_HOST') }}
        oc project {{ eap_ocp_namespace }}
        oc start-build coolstore --from-file=/tmp/ROOT.war --wait=true

    # - name: Smoke Test
