- name: Deploy Coolstore Stack on OCP
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create Coolstore namespace {{ eap_ocp_namespace }}
      k8s:
        state: present
        name: "{{ eap_ocp_namespace }}"
        api_version: project.openshift.io/v1
        kind: Project

    - name: Create Coolstore service in {{ eap_ocp_namespace }}
      k8s:
        state: present
        definition: "{{ lookup('file', 'definition.yml') }}"