- name: Deploy Coolstore Stack on OCP
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create Coolstore namespace {{ eap_ocp_namespace }}
      k8s:
        state: present
        name: "{{ eap_ocp_namespace }}"
        api_version: project.openshift.io/v1
        kind: Project

    - name: Create Coolstore objects in {{ eap_ocp_namespace }}
      k8s:
        state: present
        namespace: "{{ eap_ocp_namespace }}"
        definition: "{{ lookup('file', 'definition.yml') }}"

    - debug:
        msg: "{{ lookup('template', 'jboss_secrets.j2') }}"

    - name: Create Coolstore secrets {{ eap_ocp_namespace }}
      k8s:
        state: present
        namespace: "{{ eap_ocp_namespace }}"
        definition: "{{ lookup('template', 'jboss_secrets.j2') }}"
